apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notebook-search-app.fullname" . }}-config
  labels:
    {{- include "notebook-search-app.labels" . | nindent 4 }}

data:
  HOST_IP : "127.0.0.0"
  ELASTICSEARCH_HOSTNAME : {{ .Release.Name }}-elasticsearch
  ELASTICSEARCH_PORT : "9200"
  ELASTICSEARCH_USERNAME : "elastic"
  ELASTICSEARCH_PASSWORD : "changeme"
  POSTGRES_HOSTNAME : {{ .Release.Name }}-postgresql
  POSTGRES_PORT : "5432"
