apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-config
  labels:
    {{- include "..labels" . | nindent 4 }}

data:
  HOST_IP : "127.0.0.0"
  ELASTICSEARCH_PORT : "9200"
  ELASTICSEARCH_USERNAME : "elastic"
  ELASTICSEARCH_PASSWORD : "changeme"
  POSTGRES_PORT : "5432"
