apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}-config
  labels:
    {{- include "..labels" . | nindent 4 }}

data:
  HOST_IP : "127.0.0.0"
  ELASTICSEARCH_HOSTNAME : {{ .Release.Name }}-elasticsearch
  ELASTICSEARCH_PORT : "9200"
  ELASTICSEARCH_USERNAME : "elastic"
  ELASTICSEARCH_PASSWORD : "changeme"
  POSTGRES_HOSTNAME : {{ .Release.Name }}-postgresql-hl
  POSTGRES_PORT : "5432"
  POSTGRES_USER : {{ .Values.postgresql.auth.username }}
  POSTGRES_DB : {{ .Values.postgresql.auth.database }}
