apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- if not .Values.searchengineapp.autoscaling.enabled }}
  replicas: {{ .Values.searchengineapp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.searchengineapp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.searchengineapp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.searchengineapp.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.searchengineapp.securityContext | nindent 12 }}
          image: "{{ .Values.searchengineapp.image.repository }}:{{ .Values.searchengineapp.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.searchengineapp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.searchengineapp.resources | nindent 12 }}
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
            - name: HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: HOST_IP
            - name: ELASTICSEARCH_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_HOSTNAME
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_PORT
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_PASSWORD
            - name: POSTGRES_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_HOSTNAME
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_DB


      {{- with .Values.searchengineapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searchengineapp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.searchengineapp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
