apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "..fullname" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  {{- if not .Values.search_engine_app.autoscaling.enabled }}
  replicas: {{ .Values.search_engine_app.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "..selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.search_engine_app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "..selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.search_engine_app.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "..serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.search_engine_app.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.search_engine_app.securityContext | nindent 12 }}
          image: "{{ .Values.search_engine_app.image.repository }}:{{ .Values.search_engine_app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.search_engine_app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 7777
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: {{ .Values.search_engine_app.service.test_path }}
#              port: {{ .Values.search_engine_app.service.port }}
#          readinessProbe:
#            httpGet:
#              path: {{ .Values.search_engine_app.service.test_path }}
#              port: {{ .Values.search_engine_app.service.port }}
          resources:
            {{- toYaml .Values.search_engine_app.resources | nindent 12 }}
          env:
            - name: HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: HOST_IP
            - name: ELASTICSEARCH_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_HOSTNAME
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_PORT
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_PASSWORD
            - name: POSTGRES_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_HOSTNAME
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_PASSWORD
#            - name: POSTGRES_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: {{ .Release.Name }}-postgresql
#                  key: password

      initContainers:
        - name: {{ .Chart.Name }}-index
          securityContext:
            {{- toYaml .Values.search_engine_app.securityContext | nindent 12 }}
          image: busybox:1.28
          command: ['sh', '-c', "echo indexing...."]
          imagePullPolicy: {{ .Values.search_engine_app.image.pullPolicy }}
          env:
            - name: HOST_IP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: HOST_IP
            - name: ELASTICSEARCH_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_HOSTNAME
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_PORT
            - name: ELASTICSEARCH_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_USERNAME
            - name: ELASTICSEARCH_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: ELASTICSEARCH_PASSWORD
            - name: POSTGRES_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_HOSTNAME
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ include "..fullname" . }}-config
                  key: POSTGRES_PASSWORD

      {{- with .Values.search_engine_app.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.search_engine_app.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.search_engine_app.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
