{{- if .Values.notebook_search_app.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "notebook-search-app.fullname" . }}
  labels:
    {{- include "notebook-search-app.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "notebook-search-app.fullname" . }}
  minReplicas: {{ .Values.notebook_search_app.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.notebook_search_app.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.notebook_search_app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.notebook_search_app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.notebook_search_app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.notebook_search_app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
