{{- if .Values.notebook_search_app.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "notebook-search-app.serviceAccountName" . }}
  labels:
    {{- include "notebook-search-app.labels" . | nindent 4 }}
  {{- with .Values.notebook_search_app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
