{{- if .Values.searchengineapp.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "..serviceAccountName" . }}
  labels:
    {{- include "..labels" . | nindent 4 }}
  {{- with .Values.searchengineapp.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
